import {
  PILOT_PROJECT_LIMITS,
  PILOT_WORKFLOW,
  PILOT_WORKFLOW_LABELS,
  type PilotChecklistItem,
  type PilotProject,
  type PilotWorkflowStatus,
  type PilotWorkflowStep,
  type PilotWorkspace,
} from "@/lib/pilot/types";

const CREATED_AT = "2026-06-02T14:00:00.000Z";
const NOW = "2026-07-12T15:00:00.000Z";
const PORTFOLIO_ID = "portfolio-meridian-001";

/**
 * Synthetic credentials for local route tests only. Production records contain
 * hashes, never these raw values. Do not reuse these outside demo mode.
 */
export const PILOT_DEMO_INVITE_TOKENS = {
  clientReview: "pilot-review-invite",
  expired: "pilot-expired-invite",
  revoked: "pilot-revoked-invite",
  ownerHandoff: "pilot-owner-invite",
  redeemedViewer: "pilot-viewer-invite",
} as const;

const branding = {
  practiceName: "Meridian Family Histories",
  logoPath: "/demo/pilot/meridian-family-histories-logo.svg",
  mark: "MFH",
  primaryColor: "#163a35",
  accentColor: "#b9874f",
  backgroundColor: "#f4efe6",
  typography: "editorial" as const,
  byline: "Curated by Meridian Family Histories",
  supportEmail: "hello@example.family",
  themeId: "heirloom" as const,
};

function workflowFor(current: PilotWorkflowStatus): PilotWorkflowStep[] {
  const currentIndex = PILOT_WORKFLOW.indexOf(current);

  return PILOT_WORKFLOW.map((status, index) => ({
    status,
    label: PILOT_WORKFLOW_LABELS[status],
    state: index < currentIndex ? "complete" : index === currentIndex ? "current" : "up_next",
    completedAt: index < currentIndex ? NOW : null,
  }));
}

function checklistFor(
  completed: boolean,
  overrides: Partial<Record<PilotChecklistItem["key"], PilotChecklistItem["status"]>> = {},
): PilotChecklistItem[] {
  const definitions: Array<
    Pick<PilotChecklistItem, "key" | "label" | "description" | "requiredForPublish">
  > = [
    {
      key: "legal_review",
      label: "Attorney review for real data",
      description: "Attorney review must be recorded before any real client data is received.",
      requiredForPublish: true,
    },
    {
      key: "rights_attestation",
      label: "Media rights attested",
      description: "The genealogist confirms authorization for every submitted asset.",
      requiredForPublish: true,
    },
    {
      key: "living_person_consent",
      label: "Living-person privacy checked",
      description: "Living adults are minimized and consented; living minors remain hidden.",
      requiredForPublish: true,
    },
    {
      key: "focal_branch",
      label: "Focal branch selected",
      description: "The opening tree has a clear person and family branch.",
      requiredForPublish: true,
    },
    {
      key: "welcome_page",
      label: "Welcome page curated",
      description: "Family name, opening message, hero, and primary action are ready.",
      requiredForPublish: true,
    },
    {
      key: "featured_stories",
      label: "Featured stories ready",
      description: "At least three sourced stories are ready, unless an operator records an override.",
      requiredForPublish: true,
    },
    {
      key: "import_review_acknowledged",
      label: "Import review acknowledged",
      description: "Every import warning is resolved or explicitly acknowledged.",
      requiredForPublish: true,
    },
    {
      key: "media_safety",
      label: "Media safety passed",
      description: "Every used asset passed signature validation and the named malware scan.",
      requiredForPublish: true,
    },
    {
      key: "professional_preview",
      label: "Professional preview complete",
      description: "The genealogist reviewed the presentation before client access was issued.",
      requiredForPublish: true,
    },
    {
      key: "client_approval",
      label: "Client approval recorded",
      description: "The final frozen review version has explicit client approval.",
      requiredForPublish: true,
    },
  ];

  return definitions.map((definition) => {
    const status = overrides[definition.key] ?? (completed ? "complete" : "pending");
    return {
      ...definition,
      status,
      completedAt: status === "pending" ? null : NOW,
      completedByActorId: status === "pending" ? null : "actor-operator",
      evidenceReference:
        status === "complete" ? `demo-evidence://${definition.key}` : null,
      overrideReason:
        status === "waived" ? "Operator-approved story-light presentation." : null,
    };
  });
}

function emptyMetrics() {
  return {
    conciergeMinutes: 0,
    genealogistSetupMinutes: 0,
    importSucceeded: false,
    importedPeople: 0,
    importWarningCount: 0,
    clientViewerCount: 0,
    clientShareCount: 0,
    repeatProject: false,
    acquisitionCostCents: 0,
    grossSalesCents: 0,
    cashCostCents: 0,
    refundCents: 0,
    privacyIncidentCount: 0,
  };
}

const hartProject: PilotProject = {
  id: "pilot-hart-001",
  slug: "hart-family-legacy",
  portfolioId: PORTFOLIO_ID,
  treeId: "tree-hart",
  title: "The Hart Family Legacy",
  clientLabel: "Hart family · founding demonstration",
  focalPersonId: "p03",
  status: "handoff",
  workflow: workflowFor("handoff"),
  scope: { ...PILOT_PROJECT_LIMITS },
  counts: {
    people: 20,
    mediaItems: 9,
    mediaBytes: 63_400_000,
    featuredStories: 3,
    unresolvedImportIssues: 0,
  },
  branding,
  welcome: {
    eyebrow: "A private family history",
    familyName: "The Hart Family",
    headline: "Four generations, one unfolding story.",
    introduction:
      "Follow the letters, photographs, and small acts of care that kept the Hart family connected across Kentucky and Indiana.",
    heroMediaId: "media-hart-hero",
    primaryActionLabel: "Explore your family",
  },
  checklist: checklistFor(true, { legal_review: "pending" }),
  importSummary: {
    importJobId: "job01",
    fileName: "hart-family-demo.ged",
    importedAt: "2026-06-03T13:20:00.000Z",
    stagingExpiresAt: "2026-06-10T13:20:00.000Z",
    parserStatus: "confirmed",
    sourceSystem: "gedcom",
    peopleCount: 20,
    familyCount: 7,
    sourceCount: 1,
    focalPersonId: "p03",
    issues: [
      {
        id: "pilot-import-issue-01",
        subjectType: "person",
        subjectId: "p20",
        severity: "warning",
        title: "Unlinked person",
        description: "Marjorie Reed has no verified family connection in the imported file.",
        status: "acknowledged",
        disposition: "Preserved as an unlinked research lead and excluded from the opening view.",
      },
    ],
  },
  media: [
    {
      id: "media-hart-hero",
      projectId: "pilot-hart-001",
      kind: "image",
      fileName: "hart-family-collage.webp",
      mimeType: "image/webp",
      byteSize: 4_800_000,
      sha256: "a".repeat(64),
      originalStoragePath: "private/pilot-hart-001/originals/hart-family-collage.webp",
      derivativePath: "/demo/pilot/hart-family-hero.svg",
      inertPreviewPath: null,
      caption: "A synthetic collage representing the Hart family archive.",
      altText: "Layered Hart family portraits, handwritten notes, and a pressed botanical specimen.",
      decorative: false,
      provenance: "Synthetic demonstration artwork; no real family media.",
      rightsBasis: "family_owned",
      rightsEvidenceReference: "demo-rights://synthetic-assets",
      consentStatus: "not_required",
      visibility: "invited_family",
      linkedPersonIds: ["p01", "p02", "p03", "p04"],
      sourceIds: ["src01"],
      featured: true,
      quarantineStatus: "passed",
      signatureStatus: "passed",
      malwareScanStatus: "passed",
      malwareScanProcedure: "Demo-ClamAV-1.4 signature scan",
      quarantineCheckedAt: "2026-06-04T10:00:00.000Z",
      quarantineCheckedByActorId: "actor-operator",
      quarantineFailureReason: null,
      uploadedAt: "2026-06-04T09:40:00.000Z",
    },
    // Portraits are generated period photographs of people who never existed;
    // see docs/design/ancestor-portrait-prompts.md. Margaret is recorded as
    // living, so she is hidden from the presentation and keeps the placeholder.
    ...[
      ["josiah", "Josiah Hart", "p21", "portraits/josiah.webp"],
      ["martha", "Martha Ellen Hart", "p22", "portraits/martha.webp"],
      ["walter", "Walter Hart", "p01", "portraits/walter.webp"],
      ["june", "June Mercer Hart", "p02", "portraits/june.webp"],
      ["eleanor", "Eleanor Hart West", "p03", "portraits/eleanor.webp"],
      ["robert", "Robert Hart", "p04", "portraits/robert.webp"],
      ["samuel", "Samuel West", "p05", "portraits/samuel.webp"],
      ["margaret", "Margaret West Vale", "p06", "portrait-margaret-west-vale.svg"],
    ].map(([key, name, personId, path], index) => ({
      id: `media-portrait-${key}`,
      projectId: "pilot-hart-001",
      kind: "image" as const,
      fileName: `${key}-portrait.webp`,
      mimeType: "image/webp" as const,
      byteSize: 4_200_000 + index * 90_000,
      sha256: String(index + 1).repeat(64),
      originalStoragePath: `private/pilot-hart-001/originals/${key}-portrait.webp`,
      derivativePath: `/demo/pilot/${path}`,
      inertPreviewPath: null,
      caption: `${name}, synthetic demonstration portrait.`,
      altText: `Synthetic archival portrait of ${name}.`,
      decorative: false,
      provenance: "Synthetic demonstration artwork; no real family media.",
      rightsBasis: "family_owned" as const,
      rightsEvidenceReference: "demo-rights://synthetic-assets",
      consentStatus: personId === "p06" ? ("granted" as const) : ("not_required" as const),
      visibility: "invited_family" as const,
      linkedPersonIds: [personId],
      sourceIds: [] as string[],
      featured: personId === "p03",
      quarantineStatus: "passed" as const,
      signatureStatus: "passed" as const,
      malwareScanStatus: "passed" as const,
      malwareScanProcedure: "Demo-ClamAV-1.4 signature scan",
      quarantineCheckedAt: "2026-06-04T10:00:00.000Z",
      quarantineCheckedByActorId: "actor-operator",
      quarantineFailureReason: null,
      uploadedAt: "2026-06-04T09:45:00.000Z",
    })),
    {
      id: "media-reunion-circular",
      projectId: "pilot-hart-001",
      kind: "pdf",
      fileName: "1968-hart-reunion-circular.pdf",
      mimeType: "application/pdf",
      byteSize: 8_100_000,
      sha256: "8".repeat(64),
      originalStoragePath: "private/pilot-hart-001/originals/1968-hart-reunion-circular.pdf",
      derivativePath: null,
      inertPreviewPath: "/demo/pilot/record-hart-reunion-circular.svg",
      caption: "Hart reunion circular, 1968.",
      altText: "Inert preview of a typed 1968 Hart family reunion circular.",
      decorative: false,
      provenance: "Synthetic record based on the existing demo source src01.",
      rightsBasis: "family_owned",
      rightsEvidenceReference: "demo-rights://synthetic-assets",
      consentStatus: "not_required",
      visibility: "invited_family",
      linkedPersonIds: ["p02"],
      sourceIds: ["src01"],
      featured: true,
      quarantineStatus: "passed",
      signatureStatus: "passed",
      malwareScanStatus: "passed",
      malwareScanProcedure: "Demo-ClamAV-1.4 signature scan",
      quarantineCheckedAt: "2026-06-04T10:00:00.000Z",
      quarantineCheckedByActorId: "actor-operator",
      quarantineFailureReason: null,
      uploadedAt: "2026-06-04T09:50:00.000Z",
    },
    {
      id: "media-failed-scan",
      projectId: "pilot-hart-001",
      kind: "image",
      fileName: "damaged-envelope-scan.png",
      mimeType: "image/png",
      byteSize: 2_600_000,
      sha256: "9".repeat(64),
      originalStoragePath: "quarantine/pilot-hart-001/damaged-envelope-scan.png",
      derivativePath: null,
      inertPreviewPath: null,
      caption: "Isolated upload; never displayed or exported.",
      altText: null,
      decorative: true,
      provenance: "Synthetic rejected-upload example.",
      rightsBasis: "family_owned",
      rightsEvidenceReference: "demo-rights://synthetic-assets",
      consentStatus: "not_required",
      visibility: "private",
      linkedPersonIds: [],
      sourceIds: [],
      featured: false,
      quarantineStatus: "failed",
      signatureStatus: "failed",
      malwareScanStatus: "pending",
      malwareScanProcedure: null,
      quarantineCheckedAt: "2026-06-04T10:02:00.000Z",
      quarantineCheckedByActorId: "actor-operator",
      quarantineFailureReason: "File signature did not match the declared PNG type; file was not parsed.",
      uploadedAt: "2026-06-04T09:55:00.000Z",
    },
  ],
  stories: [
    {
      id: "story-cedar-chest",
      projectId: "pilot-hart-001",
      title: "The cedar chest that kept the family together",
      dek: "Walter saved the scraps other people would have thrown away.",
      bodyMd:
        "Inside Walter Hart’s cedar chest were railway stubs, reunion programs, and decades of letters. Those ordinary papers became the thread that let later generations reconstruct the family’s shared life.",
      coverMediaId: "media-portrait-walter",
      personIds: ["p01", "p02"],
      sourceIds: ["src01"],
      visibility: "invited_family",
      featured: true,
      order: 1,
      status: "published",
    },
    {
      id: "story-porch-suppers",
      projectId: "pilot-hart-001",
      title: "June’s porch suppers",
      dek: "A handwritten invitation became a reunion tradition.",
      bodyMd:
        "June Mercer Hart used music, food, and a reliable mailing list to keep distant cousins close. Her 1968 circular is the earliest surviving record of a gathering that continued for decades.",
      coverMediaId: "media-portrait-june",
      personIds: ["p02", "p03", "p04"],
      sourceIds: ["src01"],
      visibility: "invited_family",
      featured: true,
      order: 2,
      status: "published",
    },
    {
      id: "story-eleanor-index",
      projectId: "pilot-hart-001",
      title: "Eleanor names the faces",
      dek: "One careful archivist turned boxes of photographs into a navigable history.",
      bodyMd:
        "Eleanor Hart West wrote names and dates on the backs of photographs, then built an index by household and year. Her quiet work is why so many faces in the archive still have names.",
      coverMediaId: "media-portrait-eleanor",
      personIds: ["p03", "p05", "p06"],
      sourceIds: ["src01"],
      visibility: "invited_family",
      featured: true,
      order: 3,
      status: "published",
    },
  ],
  consents: [
    {
      id: "consent-p06",
      projectId: "pilot-hart-001",
      personId: "p06",
      subjectLabel: "Margaret West Vale",
      subjectKind: "living_adult",
      status: "granted",
      allowedFields: ["display_name", "relationship", "portrait"],
      evidenceReference: "demo-consent://p06",
      recordedAt: "2026-06-05T13:00:00.000Z",
      recordedByActorId: "actor-operator",
      hiddenByDefault: false,
    },
    {
      id: "consent-p19",
      projectId: "pilot-hart-001",
      personId: "p19",
      subjectLabel: "Living minor",
      subjectKind: "living_minor",
      status: "required",
      allowedFields: [],
      evidenceReference: null,
      recordedAt: null,
      recordedByActorId: null,
      hiddenByDefault: true,
    },
  ],
  roles: [
    {
      id: "role-hart-operator",
      projectId: "pilot-hart-001",
      actorId: "actor-operator",
      identityId: "acct-demo-owner",
      displayName: "Pilot operator",
      role: "operator",
      status: "active",
      grantedAt: CREATED_AT,
      expiresAt: null,
      revokedAt: null,
    },
    {
      id: "role-hart-genealogist",
      projectId: "pilot-hart-001",
      actorId: "actor-genealogist",
      identityId: "identity-genealogist",
      displayName: "Maya Bell, CG",
      role: "genealogist",
      status: "active",
      grantedAt: CREATED_AT,
      expiresAt: "2026-08-09T16:00:00.000Z",
      revokedAt: null,
    },
    {
      id: "role-hart-reviewer",
      projectId: "pilot-hart-001",
      actorId: "actor-reviewer",
      identityId: null,
      displayName: "Designated client reviewer",
      role: "client_reviewer",
      status: "active",
      grantedAt: "2026-06-20T14:00:00.000Z",
      expiresAt: "2027-01-05T14:00:00.000Z",
      revokedAt: null,
    },
    {
      id: "role-hart-owner",
      projectId: "pilot-hart-001",
      actorId: "actor-owner",
      identityId: "identity-hart-owner",
      displayName: "Leah Hart",
      role: "owner_candidate",
      status: "pending",
      grantedAt: "2026-07-09T15:30:00.000Z",
      expiresAt: null,
      revokedAt: null,
    },
  ],
  invites: [
    {
      id: "invite-hart-issued",
      projectId: "pilot-hart-001",
      recipientId: "recipient-client-reviewer",
      recipientLabel: "Designated client reviewer",
      recipientEmail: "reviewer@example.family",
      purpose: "client_review",
      tokenHash: "f76d00608cc70808f620439a8856ea7a42ab621457bc9494b9cf7d2c40164de7",
      tokenHint: "…vite",
      status: "issued",
      issuedAt: "2026-07-12T14:00:00.000Z",
      expiresAt: "2027-01-05T14:00:00.000Z",
      redeemedAt: null,
      revokedAt: null,
      reissuedFromInviteId: null,
    },
    {
      id: "invite-hart-redeemed",
      projectId: "pilot-hart-001",
      recipientId: "recipient-cousin-jon",
      recipientLabel: "Jon West",
      recipientEmail: "jon@example.family",
      purpose: "viewer",
      tokenHash: "a859f1f120370e502be6af012a494a9f899e59d9eae32781b6b6338bbeca80b7",
      tokenHint: "…K8RP",
      status: "redeemed",
      issuedAt: "2026-07-08T14:00:00.000Z",
      expiresAt: "2026-07-15T14:00:00.000Z",
      redeemedAt: "2026-07-09T13:15:00.000Z",
      revokedAt: null,
      reissuedFromInviteId: null,
    },
    {
      id: "invite-hart-expired",
      projectId: "pilot-hart-001",
      recipientId: "recipient-aunt-mary",
      recipientLabel: "Mary Hart",
      recipientEmail: "mary@example.family",
      purpose: "viewer",
      tokenHash: "6560aed67bef4fca8ed11ddebd7ca1b0056f68c34553f8116d68b26d0c4e8878",
      tokenHint: "…P4LX",
      status: "expired",
      issuedAt: "2026-06-20T14:00:00.000Z",
      expiresAt: "2026-06-27T14:00:00.000Z",
      redeemedAt: null,
      revokedAt: null,
      reissuedFromInviteId: null,
    },
    {
      id: "invite-hart-revoked",
      projectId: "pilot-hart-001",
      recipientId: "recipient-old-address",
      recipientLabel: "Old address",
      recipientEmail: "old-address@example.family",
      purpose: "viewer",
      tokenHash: "6ed8496957c2ead30d2740e8678b98f9a20c8c88dc89363ca34bb756a199b6b9",
      tokenHint: "…M2TW",
      status: "revoked",
      issuedAt: "2026-07-01T14:00:00.000Z",
      expiresAt: "2026-07-08T14:00:00.000Z",
      redeemedAt: null,
      revokedAt: "2026-07-02T14:00:00.000Z",
      reissuedFromInviteId: null,
    },
    {
      id: "invite-hart-owner",
      projectId: "pilot-hart-001",
      recipientId: "recipient-archive-owner",
      recipientLabel: "Leah Hart",
      recipientEmail: "owner@example.family",
      purpose: "owner_handoff",
      tokenHash: "63555e4095b4b18bad5e4476049fd463fef05feb844f2b6902bb23d69903b15a",
      tokenHint: "…vite",
      status: "issued",
      issuedAt: "2026-07-09T15:30:00.000Z",
      expiresAt: "2027-01-05T15:30:00.000Z",
      redeemedAt: null,
      revokedAt: null,
      reissuedFromInviteId: null,
    },
  ],
  sessions: [
    {
      id: "session-hart-jon",
      projectId: "pilot-hart-001",
      recipientId: "recipient-cousin-jon",
      inviteId: "invite-hart-redeemed",
      sessionTokenHash: "f".repeat(64),
      createdAt: "2026-07-09T13:15:00.000Z",
      lastSeenAt: "2026-07-12T12:00:00.000Z",
      idleExpiresAt: "2026-07-26T12:00:00.000Z",
      absoluteExpiresAt: "2026-08-08T13:15:00.000Z",
      revokedAt: null,
    },
  ],
  revisions: [
    {
      id: "revision-hart-001",
      projectId: "pilot-hart-001",
      sequence: 1,
      basedOnRevisionId: null,
      status: "superseded",
      createdAt: "2026-06-20T14:00:00.000Z",
      createdByActorId: "actor-genealogist",
      approvedAt: null,
      publishedAt: null,
    },
    {
      id: "revision-hart-002",
      projectId: "pilot-hart-001",
      sequence: 2,
      basedOnRevisionId: "revision-hart-001",
      status: "published",
      createdAt: "2026-07-02T14:00:00.000Z",
      createdByActorId: "actor-genealogist",
      approvedAt: "2026-07-09T14:00:00.000Z",
      publishedAt: "2026-07-09T15:00:00.000Z",
    },
  ],
  reviewVersions: [
    {
      id: "review-hart-round-1",
      projectId: "pilot-hart-001",
      revisionId: "revision-hart-001",
      round: 1,
      label: "Client review · Round 1",
      status: "resolved",
      contentFingerprint: "1".repeat(64),
      createdAt: "2026-06-20T14:00:00.000Z",
      openedAt: "2026-06-21T14:00:00.000Z",
      frozenAt: "2026-06-28T14:00:00.000Z",
      submittedAt: "2026-06-28T14:00:00.000Z",
      approvedAt: null,
      submittedByActorId: "actor-reviewer",
    },
    {
      id: "review-hart-round-2",
      projectId: "pilot-hart-001",
      revisionId: "revision-hart-002",
      round: 2,
      label: "Final client review",
      status: "approved",
      contentFingerprint: "2".repeat(64),
      createdAt: "2026-07-02T14:00:00.000Z",
      openedAt: "2026-07-03T14:00:00.000Z",
      frozenAt: "2026-07-09T14:00:00.000Z",
      submittedAt: "2026-07-09T14:00:00.000Z",
      approvedAt: "2026-07-09T14:00:00.000Z",
      submittedByActorId: "actor-reviewer",
    },
  ],
  reviewItems: [
    {
      id: "review-item-hart-01",
      projectId: "pilot-hart-001",
      reviewVersionId: "review-hart-round-1",
      subjectType: "story",
      subjectId: "story-porch-suppers",
      fieldPath: "bodyMd",
      request: "Clarify that the porch supper began before the typed 1968 circular.",
      status: "resolved",
      disposition: "Accepted; wording now distinguishes the tradition from the surviving record.",
      resolvedAt: "2026-07-01T14:00:00.000Z",
      resolvedByActorId: "actor-genealogist",
    },
    {
      id: "review-item-hart-02",
      projectId: "pilot-hart-001",
      reviewVersionId: "review-hart-round-2",
      subjectType: "media",
      subjectId: "media-portrait-eleanor",
      fieldPath: "caption",
      request: "Use Eleanor’s married name in the portrait caption.",
      status: "resolved",
      disposition: "Accepted; caption updated to Eleanor Hart West.",
      resolvedAt: "2026-07-08T14:00:00.000Z",
      resolvedByActorId: "actor-genealogist",
    },
  ],
  publication: {
    revisionId: "revision-hart-002",
    publishedAt: "2026-07-09T15:00:00.000Z",
    publishedByActorId: "actor-operator",
    privatePath: "/s/hart-family-legacy",
    noIndex: true,
  },
  handoff: {
    id: "handoff-hart-001",
    projectId: "pilot-hart-001",
    ownerActorId: "actor-owner",
    ownerIdentityId: "identity-hart-owner",
    status: "pending",
    identityVerifiedAt: "2026-07-10T15:30:00.000Z",
    invitedAt: "2026-07-09T15:30:00.000Z",
    acceptedAt: null,
    professionalSupportExpiresAt: null,
    supportExtensionCount: 0,
  },
  exports: [],
  deletion: null,
  audit: [
    {
      id: "audit-hart-01",
      projectId: "pilot-hart-001",
      actorId: "actor-operator",
      type: "checklist_updated",
      occurredAt: "2026-06-05T14:00:00.000Z",
      summary: "Legal, rights, privacy, and media safety gates were recorded.",
      metadata: { synthetic: true },
    },
    {
      id: "audit-hart-02",
      projectId: "pilot-hart-001",
      actorId: "actor-reviewer",
      type: "review_submitted",
      occurredAt: "2026-06-28T14:00:00.000Z",
      summary: "Client review round one was frozen and submitted.",
      metadata: { round: 1, reviewVersionId: "review-hart-round-1" },
    },
    {
      id: "audit-hart-03",
      projectId: "pilot-hart-001",
      actorId: "actor-reviewer",
      type: "client_approved",
      occurredAt: "2026-07-09T14:00:00.000Z",
      summary: "The client approved final review version 2.",
      metadata: { round: 2, reviewVersionId: "review-hart-round-2" },
    },
    {
      id: "audit-hart-04",
      projectId: "pilot-hart-001",
      actorId: "actor-operator",
      type: "project_published",
      occurredAt: "2026-07-09T15:00:00.000Z",
      summary: "The approved Hart presentation was privately published.",
      metadata: { revisionId: "revision-hart-002", noIndex: true },
    },
    {
      id: "audit-hart-05",
      projectId: "pilot-hart-001",
      actorId: "actor-operator",
      type: "invite_issued",
      occurredAt: "2026-07-09T15:30:00.000Z",
      summary: "A verified-owner handoff invitation was issued to Leah Hart.",
      metadata: { inviteId: "invite-hart-owner", purpose: "owner_handoff" },
    },
  ],
  metrics: {
    conciergeMinutes: 245,
    genealogistSetupMinutes: 28,
    importSucceeded: true,
    importedPeople: 20,
    importWarningCount: 1,
    clientViewerCount: 7,
    clientShareCount: 3,
    repeatProject: false,
    acquisitionCostCents: 1_800,
    grossSalesCents: 24_900,
    cashCostCents: 2_100,
    refundCents: 0,
    privacyIncidentCount: 0,
  },
  legalReviewCompletedAt: "2026-06-05T14:00:00.000Z",
  createdAt: CREATED_AT,
  updatedAt: NOW,
};

function createPipelineProject(input: {
  id: string;
  slug: string;
  title: string;
  clientLabel: string;
  status: PilotWorkflowStatus;
  focalPersonId: string;
  people: number;
  issueCount: number;
}): PilotProject {
  return {
    id: input.id,
    slug: input.slug,
    portfolioId: PORTFOLIO_ID,
    // Each project owns its own archive; importing for one client must never
    // overwrite another's. Only the flagship Hart project uses the seeded tree.
    treeId: `tree-${input.id}`,
    title: input.title,
    clientLabel: input.clientLabel,
    focalPersonId: input.focalPersonId,
    status: input.status,
    workflow: workflowFor(input.status),
    scope: { ...PILOT_PROJECT_LIMITS },
    counts: {
      people: input.people,
      mediaItems: 0,
      mediaBytes: 0,
      featuredStories: 0,
      unresolvedImportIssues: input.issueCount,
    },
    branding,
    welcome: {
      eyebrow: "Private family history",
      familyName: input.title,
      headline: "A family story in progress.",
      introduction: "Complete curation to preview this private presentation.",
      heroMediaId: null,
      primaryActionLabel: "Explore your family",
    },
    checklist: checklistFor(false),
    importSummary: {
      importJobId: `${input.id}-import`,
      fileName: `${input.slug}.ged`,
      importedAt: NOW,
      stagingExpiresAt: "2026-07-19T15:00:00.000Z",
      parserStatus: input.status === "intake" || input.status === "materials" ? "pending" : "parsed",
      sourceSystem: "gedcom",
      peopleCount: input.people,
      familyCount: Math.max(0, Math.floor(input.people / 3)),
      sourceCount: 1,
      focalPersonId: input.focalPersonId,
      issues: input.issueCount
        ? [
            {
              id: `${input.id}-issue-01`,
              subjectType: "person",
              subjectId: "p20",
              severity: "warning",
              title: "Possible unlinked record",
              description: "Confirm whether this person belongs in the focal branch.",
              status: "open",
              disposition: null,
            },
          ]
        : [],
    },
    media: [],
    stories: [],
    consents: [],
    roles: [
      {
        id: `${input.id}-role-operator`,
        projectId: input.id,
        actorId: "actor-operator",
        identityId: "acct-demo-owner",
        displayName: "Pilot operator",
        role: "operator",
        status: "active",
        grantedAt: CREATED_AT,
        expiresAt: null,
        revokedAt: null,
      },
      {
        id: `${input.id}-role-genealogist`,
        projectId: input.id,
        actorId: "actor-genealogist",
        identityId: "identity-genealogist",
        displayName: "Maya Bell, CG",
        role: "genealogist",
        status: "active",
        grantedAt: CREATED_AT,
        expiresAt: null,
        revokedAt: null,
      },
    ],
    invites: [],
    sessions: [],
    revisions: [
      {
        id: `${input.id}-revision-001`,
        projectId: input.id,
        sequence: 1,
        basedOnRevisionId: null,
        status: "draft",
        createdAt: CREATED_AT,
        createdByActorId: "actor-genealogist",
        approvedAt: null,
        publishedAt: null,
      },
    ],
    reviewVersions: [],
    reviewItems: [],
    publication: null,
    handoff: null,
    exports: [],
    deletion: null,
    audit: [],
    metrics: {
      ...emptyMetrics(),
      importedPeople: input.people,
      importWarningCount: input.issueCount,
    },
    legalReviewCompletedAt: null,
    createdAt: CREATED_AT,
    updatedAt: NOW,
  };
}

export function createPilotDemoWorkspace(): PilotWorkspace {
  const reviewProject = createPipelineProject({
    id: "pilot-brooks-003",
    slug: "brooks-family-journey",
    title: "The Brooks Family Journey",
    clientLabel: "Client review · synthetic",
    status: "client_review_round_1",
    focalPersonId: "p14",
    people: 43,
    issueCount: 0,
  });
  reviewProject.revisions[0]!.status = "in_review";
  reviewProject.reviewVersions.push({
    id: "review-brooks-round-1",
    projectId: reviewProject.id,
    revisionId: reviewProject.revisions[0]!.id,
    round: 1,
    label: "Client review · Round 1",
    status: "open",
    contentFingerprint: "3".repeat(64),
    createdAt: NOW,
    openedAt: NOW,
    frozenAt: null,
    submittedAt: null,
    approvedAt: null,
    submittedByActorId: null,
  });
  reviewProject.roles.push({
    id: "pilot-brooks-003-role-reviewer",
    projectId: reviewProject.id,
    actorId: "actor-brooks-reviewer",
    identityId: null,
    displayName: "Brooks client reviewer",
    role: "client_reviewer",
    status: "active",
    grantedAt: NOW,
    expiresAt: "2027-01-05T15:00:00.000Z",
    revokedAt: null,
  });

  const projects = [
    hartProject,
    createPipelineProject({
      id: "pilot-vale-002",
      slug: "vale-branch-showcase",
      title: "The Vale Branch",
      clientLabel: "Import review · synthetic",
      status: "import_review",
      focalPersonId: "p06",
      people: 86,
      issueCount: 3,
    }),
    reviewProject,
  ];

  return structuredClone({
    portfolio: {
      id: PORTFOLIO_ID,
      ownerIdentityId: "acct-demo-owner",
      practiceName: branding.practiceName,
      practitionerName: "Maya Bell, CG",
      descriptor: "Private family histories, presented with care.",
      projectIds: projects.map((project) => project.id),
      branding,
    },
    activeProjectId: hartProject.id,
    projects,
  });
}

export const pilotDemoWorkspace = createPilotDemoWorkspace();
